const bodyImage=new Image();let bodyReady=false;
const bodyAssetPromise=new Promise(resolve=>{bodyImage.onload=()=>{bodyReady=true;render();resolve(true)};bodyImage.onerror=()=>{toast('人物素材加载失败，请联网刷新');resolve(false)};bodyImage.src='wardrobe/body.png'});
function unlockGirl(){if(!state.avatar&&state.completed>=1){state.avatar={character:64,clot:65,pant:66,hair:68,mask:null,cset:null};save();return true}return false}
function equipOutfit(i){if(!state.avatar){toast('完成第一个待办，就能解锁女角色');return}if(i===64){toast('女角色已解锁，挑选喜欢的穿搭吧');return}if(Object.values(state.avatar).includes(i)){toast('已经穿戴这件服饰');return}if(!state.bag[i]){toast('完成待办有机会获得这件服饰');return}const part=roomSpecs[i].part,old=state.avatar[part];if(Number.isInteger(old))state.bag[old]++;state.bag[i]--;state.avatar[part]=i;if(part==='cset'){for(const slot of ['clot','pant']){if(Number.isInteger(state.avatar[slot]))state.bag[state.avatar[slot]]++;state.avatar[slot]=null}}else if(part==='clot'||part==='pant'){if(Number.isInteger(state.avatar.cset))state.bag[state.avatar.cset]++;state.avatar.cset=null}save();render();toast('已穿戴'+furniture[i])}
function renderAvatar(){const c=$('#characterPreview'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.imageSmoothingEnabled=false;g.fillStyle='#fff3d8';g.fillRect(0,0,c.width,c.height);const outfit=state.avatar||{clot:65,pant:66,hair:68};if(atlasReady&&bodyReady){g.save();g.translate(40,10);g.scale(2,2);g.drawImage(bodyImage,600,150,80,150,0,0,80,150);for(const part of ['clot','pant','cset','hair','mask']){const a=art[outfit[part]];if(!a)continue;const sourceY=part==='hair'?150:part==='mask'?0:300;g.drawImage(a.canvas,600,sourceY,80,150,0,0,80,150)}g.restore()}$('#characterStatus').textContent=state.avatar?'女角色 · 已解锁':'女角色 · 待解锁';$('#characterHint').textContent=state.avatar?'点击衣橱里的服饰，即可更换穿搭':'完成第一个待办，领取女角色和基础穿搭';$('#removeAccessory').disabled=!state.avatar||!Number.isInteger(state.avatar.mask);$('#basicOutfit').disabled=!state.avatar}
$('#removeAccessory').onclick=()=>{if(!state.avatar||!Number.isInteger(state.avatar.mask))return;state.bag[state.avatar.mask]++;state.avatar.mask=null;save();render()};
$('#basicOutfit').onclick=()=>{if(!state.avatar)return;for(const [part,id] of [['clot',65],['pant',66],['hair',68]]){if(state.avatar[part]===id)continue;if(!state.bag[id])continue;equipOutfit(id)}};
const completeBeforeCharacter=complete;complete=function(t){const wasDone=t.done;completeBeforeCharacter(t);if(!wasDone&&t.done&&unlockGirl()){render();toast('女角色和基础穿搭已解锁！打开「我的人物」查看')}};
unlockGirl();render();
